In [1]:
from sklearn.ensemble import IsolationForest
import numpy as np
np.random.seed(1)
random_data = np.random.randn(50000,2)  * 20 + 20

clf = IsolationForest( behaviour = 'new', max_samples=100, random_state = 1, contamination= 'auto')
preds = clf.fit_predict(random_data)
preds

/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_iforest.py:248: FutureWarning: 'behaviour' is deprecated in 0.22 and will be removed in 0.24. You should not pass or set this parameter.
  FutureWarning


array([-1,  1, -1, ...,  1,  1,  1])

In [ ]:
import numpy as np 

vector_row = np.array([1,2,3])

In [ ]:
vector_column = np.array([[1],[2],[3]])

In [ ]:
#creating a matrix 

matrix = np.array([[1,2],[1,2],[1,2]])

In [ ]:
type(matrix)

numpy.ndarray

In [ ]:
print(matrix)

[[1 2]
 [1 2]
 [1 2]]


In [ ]:
# Creating a sparse matrix 
#normal matrix 
from scipy import sparse

matrix = np.array([[0,0],[0,1],[3,0]])

#creating the compressed sparse row ( CSR ) matrix 

mat_spar = sparse.csr_matrix(matrix)

In [ ]:
print(mat_spar)

  (1, 1)	1
  (2, 0)	3


In [ ]:
#selecting elements from a matrix or vector 
vector = ([1,2,3,4,5,6])

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
#selecting third element from a vector 
vector[2]

3

In [ ]:
# selecting second row second coloum from matrix
matrix[1,1]

5

In [ ]:
#review 5pg & 

##Describing a Matrix 

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
matrix.shape

(3, 3)

In [ ]:
matrix.size 

9

In [ ]:
matrix.ndim

2

#Application of operations to elements 

In [ ]:
#create a function that adds 100 to something 
add100 = lambda i:i+100

In [ ]:
#create a vectorized function 
vectorized_add_100 = np.vectorize(add100)

In [ ]:
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

#finding the maximum & minimum values

In [ ]:
np.max(matrix)

9

In [ ]:
np.min(matrix)

1

In [ ]:
#using axis parameter we can apply the operation along a certain axis 
np.max(matrix, axis=0)

array([7, 8, 9])

In [ ]:
np.min(matrix,axis=1)

array([1, 4, 7])

#calculating average varience & std deviation

In [ ]:
np.mean(matrix)

5.0

In [ ]:
np.var(matrix)

6.666666666666667

In [ ]:
np.std(matrix)

2.581988897471611

In [ ]:
#just tlike before we can get axis based summarisations using the axis parameter 

#Reshaping Arrays 

In [ ]:
#refer pages 9 & 10 

#Transpose a vector or a Matrix 

In [ ]:
transposed_matrix = matrix.T

In [ ]:
transposed_matrix


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
flatten = matrix.flatten()

In [ ]:
flatten 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linalg.matrix_rank(matrix)

2

In [ ]:
#calculating the diterminant 

np.linalg.det(matrix)

0.0

In [ ]:
#Getting the diagonal of a matrix 

matrix.diagonal()

array([1, 5, 9])

In [ ]:
#finding & evalvating eigenvectors and  eigenvalues 

eigenvalues, egienvectors = np.linalg.eig(matrix)

In [ ]:
egienvectors

array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]])

In [ ]:
eigenvalues

array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16])

#Calculating dot products 

In [ ]:
vec_a = np.array([1,2,3])
vec_b = np.array([4,5,6])

np.dot(vec_a, vec_b)

32

In [ ]:
#Adding and substracting a matirix 

In [ ]:
#mutiplying a matrix 

In [ ]:
#inverting a matrix 

In [ ]:
#generating a random values 

##Wrangling Data 

In [ ]:
import pandas as pd



In [ ]:
!wget -O titanic.csv https://www.dropbox.com/s/jhptjzvw6hq2sfv/titanic.csv?dl=0

--2021-04-14 22:43:42--  https://www.dropbox.com/s/jhptjzvw6hq2sfv/titanic.csv?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 162.125.6.18, 2620:100:6019:18::a27d:412
Connecting to www.dropbox.com (www.dropbox.com)|162.125.6.18|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/jhptjzvw6hq2sfv/titanic.csv [following]
--2021-04-14 22:43:42--  https://www.dropbox.com/s/raw/jhptjzvw6hq2sfv/titanic.csv
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc2cba382fed925bf833b0575472.dl.dropboxusercontent.com/cd/0/inline/BMryK5ByqPcsj7IkMNEEsFi51OnEOsqZNG5WBJi59Mv2RLmcxieKA2350aJaZcXAOl1lno_R_ZokS9pO7FymfVbexkvGN7SAUflh790e4vN6JY4E-KY0ENASmIBKuCpk1fuFI8Kleksbyq2CbUh5tGhv/file# [following]
--2021-04-14 22:43:43--  https://uc2cba382fed925bf833b0575472.dl.dropboxusercontent.com/cd/0/inline/BMryK5ByqPcsj7IkMNEEsFi51OnEOsqZNG5WBJi59Mv2RLmcxieKA2350aJaZcXAOl1lno_R_ZokS9pO7FymfVbe

In [ ]:
data_01 = pd.read_csv('titanic.csv')

In [ ]:
data_01.head(5)

pclass  survived  ...   body                        home.dest
0     1.0       1.0  ...    NaN                     St Louis, MO
1     1.0       1.0  ...    NaN  Montreal, PQ / Chesterville, ON
2     1.0       0.0  ...    NaN  Montreal, PQ / Chesterville, ON
3     1.0       0.0  ...  135.0  Montreal, PQ / Chesterville, ON
4     1.0       0.0  ...    NaN  Montreal, PQ / Chesterville, ON

[5 rows x 14 columns]

In [ ]:
data_01.shape

(1310, 14)

In [ ]:
data_01.describe()

pclass     survived  ...         fare        body
count  1309.000000  1309.000000  ...  1308.000000  121.000000
mean      2.294882     0.381971  ...    33.295479  160.809917
std       0.837836     0.486055  ...    51.758668   97.696922
min       1.000000     0.000000  ...     0.000000    1.000000
25%       2.000000     0.000000  ...     7.895800   72.000000
50%       3.000000     0.000000  ...    14.454200  155.000000
75%       3.000000     1.000000  ...    31.275000  256.000000
max       3.000000     1.000000  ...   512.329200  328.000000

[8 rows x 7 columns]

In [ ]:
#select first row 
data_01.iloc[0]

pclass                                   1
survived                                 1
name         Allen, Miss. Elisabeth Walton
sex                                 female
age                                     29
sibsp                                    0
parch                                    0
ticket                               24160
fare                               211.338
cabin                                   B5
embarked                                 S
boat                                     2
body                                   NaN
home.dest                     St Louis, MO
Name: 0, dtype: object

In [ ]:
#select 3 row 
data_01.iloc[:4]

pclass  survived  ...   body                        home.dest
0     1.0       1.0  ...    NaN                     St Louis, MO
1     1.0       1.0  ...    NaN  Montreal, PQ / Chesterville, ON
2     1.0       0.0  ...    NaN  Montreal, PQ / Chesterville, ON
3     1.0       0.0  ...  135.0  Montreal, PQ / Chesterville, ON

[4 rows x 14 columns]

In [ ]:
#Selecting rows based on conditionals 
#show top two rows where column 'sex' is female 

data_01[data_01['sex']=='female'].head(2)

pclass  survived  ... body                        home.dest
0     1.0       1.0  ...  NaN                     St Louis, MO
2     1.0       0.0  ...  NaN  Montreal, PQ / Chesterville, ON

[2 rows x 14 columns]

In [ ]:
#add another condition AND aged above or e0qual to 65 
data_01[(data_01['sex']=='female')& (data_01['age']>=65)]


pclass  survived  ... body                home.dest
61     1.0       1.0  ...  NaN  Little Onn Hall, Staffs

[1 rows x 14 columns]

In [ ]:
#add another condition OR aged above or e0qual to 65 
data_01[(data_01['sex']=='female')| (data_01['age']>=65)]

pclass  survived  ...   body                        home.dest
0        1.0       1.0  ...    NaN                     St Louis, MO
2        1.0       0.0  ...    NaN  Montreal, PQ / Chesterville, ON
4        1.0       0.0  ...    NaN  Montreal, PQ / Chesterville, ON
6        1.0       1.0  ...    NaN                       Hudson, NY
8        1.0       1.0  ...    NaN              Bayside, Queens, NY
...      ...       ...  ...    ...                              ...
1286     3.0       1.0  ...    NaN                              NaN
1290     3.0       1.0  ...    NaN                              NaN
1300     3.0       1.0  ...    NaN                              NaN
1304     3.0       0.0  ...  328.0                              NaN
1305     3.0       0.0  ...    NaN                              NaN

[478 rows x 14 columns]

##REPLACING VALUES 

In [ ]:
ints = set([1,1,2,3,3,3,4])
print(len(ints))

4


In [ ]:
class Person:
    def person(self, name):
        self.name = name

m = Person('Michael')

m.name

TypeError: ignored

In [ ]:
def hours_to_seconds(
hours
):
    return hours * 60 * 60

hours_to_seconds(8)

SyntaxError: ignored

In [ ]:
book = {
    'title': 'The Giver',
    'author': 'Lois Lowry',
    'rating': 4.13
}

In [ ]:
book['rating']

4.13

In [ ]:
x = ("rose", "sunflower", "daisy")
type(x)

tuple

In [ ]:
car ={'a':1,'b':2,'c':3}
type(car)


dict