Remember to store the "data" folder in the same directory/path as this notebook

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Version 1: Converting your image repository into numpy arrays

In [ ]:
#loading the folder 
!wget -O images.zip https://www.dropbox.com/s/g3o9tg44udwnurq/data.zip?dl=0

--2022-02-26 12:24:51--  https://www.dropbox.com/s/g3o9tg44udwnurq/data.zip?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 162.125.67.18, 2620:100:6023:18::a27d:4312
Connecting to www.dropbox.com (www.dropbox.com)|162.125.67.18|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/g3o9tg44udwnurq/data.zip [following]
--2022-02-26 12:24:51--  https://www.dropbox.com/s/raw/g3o9tg44udwnurq/data.zip
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc3d02c6592340ad8104e6ef6ba3.dl.dropboxusercontent.com/cd/0/inline/BgcYkKiA6DNcNMRJhu0x9ylPOmn01BNT9gVr_H_-rQgTqkcwkLILKiOhzyskl4yRCt-lO8eFrrSMlEQ-2a8kM44WVxfNQHPlaDuFypQhGqO5o1ljxjUh8z0hjC0O21VSc_JPPXeW-nhjU3HuLJ07EGXm/file# [following]
--2022-02-26 12:24:51--  https://uc3d02c6592340ad8104e6ef6ba3.dl.dropboxusercontent.com/cd/0/inline/BgcYkKiA6DNcNMRJhu0x9ylPOmn01BNT9gVr_H_-rQgTqkcwkLILKiOhzyskl4yRCt-lO8eFrrSMlEQ-2a8kM44WVxfNQH

In [ ]:
!unzip images.zip -d images

In [ ]:
import os
import numpy as np
import cv2
resize_width = 100
resize_height = 100
path ='/content/images'
images = [] # List to append the images as 2D numpy arrays.
target = [] # List to append the target
originalrepo = [] # Create a repo for flattened pixels

for root, dirs, files in os.walk(path):
     for file in files:
        with open(os.path.join(root, file), "r") as auto:
            try:
                img = cv2.imread(root+'/'+file, 0)
                img = cv2.resize(img, (resize_width, resize_height)) 
                images.append(img)
                # Append the flattened image to the pixel repo
                originalrepo.append(img.flatten())
                # Append the folder where the image is to the target list
                target.append(root.replace(path,'').replace('\\','').replace('/',''))
            except Exception as e:
                print("Invalid file "+file+" skipped.")
# Convert the repo list into numpy array
originalrepo = np.array(originalrepo) 
print(originalrepo)
print(target)

[[25 25 25 ... 25 25 25]
 [ 0  0  0 ...  0  0  0]
 [12 12 12 ... 12 12 12]
 ...
 [19 19 19 ... 19 19 19]
 [60 49 56 ... 10 10 10]
 [59 50 23 ... 19 19 19]]
['dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_Xray', 'dataKnee_

# Version 2: Converting your image repository into Pandas data frames

In [ ]:
import os
import numpy as np
import cv2
from pandas import DataFrame

resize_width = 25
resize_height = 25
path = 'data'
images = [] # List to append the images as 2D numpy arrays
target =  []
originalrepo = [] # Create a repo for flattened pixels

for root, dirs, files in os.walk(path):
     for file in files:
        with open(os.path.join(root, file), "r") as auto:
            try:
                img = cv2.imread(root+'/'+file, 0)
                img = cv2.resize(img, (resize_width, resize_height)) 
                images.append(img)
                # Append the flattened image to the pixel repo
                originalrepo.append(img.flatten())
                # Append the folder where the image is to the target list
                target.append(root.replace(path,'').replace('\\','').replace('/',''))
            except Exception as e:
                print("Invalid file "+file+" skipped.")
# Convert the repo list into pandas dataframe
originalrepowtarget = DataFrame(originalrepo) 
originalrepowtarget['class']=DataFrame(target)
originalrepowtarget

['mask', 'mask', 'mask', 'mask', 'nomask', 'nomask']


0    1    2    3    4    5    6    7    8    9  ...  616  617  618  619  \
0   63   83   49  108  188   11   28  109   49  126  ...  120  101  133  179   
1  137   40   80   92  161  123  135  128  194   72  ...   19   19  118   15   
2  190  192  190  192  192  190  193  192  198  146  ...   25   39   71   79   
3   97   95   92  160  153   78  165  198  118   96  ...  190  191  187  178   
4  243  240  240  239  238  236  236  237  237  235  ...  138  122   66   92   
5  206  155  149  153  153  153  151  153  152  153  ...  147  153  142  149   

   620  621  622  623  624   class  
0  178  136  127  117  128    mask  
1   18   15   30   24   12    mask  
2   67   52   45   44   41    mask  
3  176  181  185  181  182    mask  
4   50   18   41   42   42  nomask  
5  148  146  146  146  146  nomask  

[6 rows x 626 columns]

In [ ]:
originalrepo.astype(np.float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([[  3.,   6.,   7., ...,   0.,   0.,   1.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  1.,  82.,  51., ...,  42.,  46., 106.],
       ...,
       [  2.,  10.,  19., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   2.,   0., ...,   0.,   0.,   0.]])

In [ ]:
!pip install tensorflow
!pip install --upgrade tensorflow # Make sure you get version >2.1.0import tensorflow as tf
!pip install Scipy

import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt



     |████████████████████████████████| 462 kB 5.2 MB/s 


In [ ]:
tf.convert_to_tensor(originalrepo, dtype=None, dtype_hint=None, name=None)

<tf.Tensor: shape=(8, 10000), dtype=uint8, numpy=
array([[  3,   6,   7, ...,   0,   0,   1],
       [  0,   0,   0, ...,   0,   0,   0],
       [  1,  82,  51, ...,  42,  46, 106],
       ...,
       [  2,  10,  19, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   2,   0, ...,   0,   0,   0]], dtype=uint8)>

In [ ]:
## Use this cell  to run the model with flip, rotate, colour, zoom & plot afterwards
# Add augmentations
augmentations = [rotate, flip, colour, zoom]
# Add the augmentations to the dataset
for f in augmentations:
    # Apply the augmentation, run 4 jobs in parallel.
    imgs = imgs.map(f, num_parallel_calls=1)
plot_images(imgs, n, 15)

It is up to you to use the one you like the most!